### ISSUE TITLE
Removing INSTALL_*.js causes problems

### ISSUE THREAD

**Issue by ralphhanna** [bpmnServer/bpmn-web#12]
One consideration is that these files need to be in .gitignore - because they are customized by developer so next get pull will not overwrite them
```
    const ret=copyFile('INSTALL.env', '.env');
    copyFile('./WorkflowApp/INSTALL_configuration.ts', './WorkflowApp/configuration.ts');
    copyFile('./WorkflowApp/INSTALL_configuration.js', './WorkflowApp/configuration.js');
    copyFile('./WorkflowApp/INSTALL_appDelegate.ts', './WorkflowApp/appDelegate.ts');
    copyFile('./WorkflowApp/INSTALL_appDelegate.js', './WorkflowApp/appDelegate.js');

```
So when we run setup we get errors
```
 bpmn-server.webapp@2.0.0 setup
> ts-node setup.ts

This routine will copy initial files and setup bpmn-server database
file .env created.
***************BPMNServer UNCAUGHT ERROR***********
Error: ENOENT: no such file or directory, copyfile './WorkflowApp/INSTALL_configuration.js' -> './WorkflowApp/configuration.js'
    at Object.copyFileSync (node:fs:3003:11)
    at copyFile (/home/ubuntu/temp/bpmn-web/setup.ts:76:12)
    at copyFiles (/home/ubuntu/temp/bpmn-web/setup.ts:68:5)
    at /home/ubuntu/temp/bpmn-web/setup.ts:21:23
    at Generator.next (<anonymous>)
    at /home/ubuntu/temp/bpmn-web/setup.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/temp/bpmn-web/setup.ts:4:12)
    at main (/home/ubuntu/temp/bpmn-web/setup.ts:25:12)
    at Object.<anonymous> (/home/ubuntu/temp/bpmn-web/setup.ts:14:1) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: './WorkflowApp/INSTALL_configuration.js',
  dest: './WorkflowApp/configuration.js'
}

```

**Comment by linonetwo** [comment]
I think you can safely remove

```
copyFile('./WorkflowApp/INSTALL_configuration.js', './WorkflowApp/configuration.js');

copyFile('./WorkflowApp/INSTALL_appDelegate.js', './WorkflowApp/appDelegate.js');
```

because they will be generated in dist folder later.

**Comment by ralphhanna** [comment]
fixed
