### ISSUE TITLE
Property 'userService' does not exist on type 'BPMNServer'.ts(2339)

### ISSUE THREAD

**Issue by linonetwo** [bpmnServer/bpmn-web#2]
![图片](https://github.com/bpmnServer/bpmn-web/assets/3746270/0b99d964-acfb-41ad-9053-ee45b47fd4a7)

Also get this in runtime

```
pnpm run setup 


> bpmn-server.webapp@2.0.0 setup E:\repo\bpmn-web
> node setup.js

This routine will copy initial files and setup bpmn-server database
Installing a new Database
current directory is E:\repo\bpmn-web
Installing a new Database based on configuration in current directory
current directory is E:\repo\bpmn-web
database configuration: {
  MongoDB: {
    db_url: 'mongodb+srv://linonetwo:ooaZxxxxxxxxxx@cluster0.ep8indh.mongodb.net/?retryWrites=true&w=majority'
  },
  SQLite: { db_connection: '' }
}
server started..
(node:32480) [DEP0170] DeprecationWarning: The URL mongodb://linonetwo:ooaZxxxxxxxxxx@ac-yloxf1i-shard-00-01.ep8indh.mongodb.net:27017,ac-yloxf1i-shard-00-02.ep8indh.mongodb.net:27017,ac-yloxf1i-shard-00-00.ep8indh.mongodb.net:27017/?authSource=admin&replicaSet=atlas-ij1mk4-shard-0&retryWrites=true&w=majority&ssl=true is invalid. Future versions of Node.js will throw an error.
(Use `node --trace-deprecation ...` to show where the warning was created)
index named "id_1" was created for collection "wf_instances"
index named "items.id_1" was created for collection "wf_instances"
index named "id_1" was created for collection "wf_locks"
index named "name_1" was created for collection "wf_models"
TypeError: Cannot read properties of undefined (reading 'install')
    at E:\repo\bpmn-web\setup.js:95:38
    at Generator.next (<anonymous>)
    at fulfilled (E:\repo\bpmn-web\setup.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
---done.
Error No timeDuration is defined
Error No timeDuration is defined
Error No timeDuration is defined
Error No timeDuration is defined
Error No timeDuration is defined
Error No timeDuration is defined


UPGRADE WARNING: Listing of Potential invalid expressions:
------------------------------------------------------------
    If you are upgrading from an earlier release, Please note: bpmn-server release 2.0.0 and higher requires all script expression to start with $
    Older releases can have expression like this:
        data.val1==5
    now:
        $data.val1==5
    or if you prefer
        $(data.val1==5)

    This report lists all expression scripts for models in your installation
    Please verify that they have the correct syntax
    We recommend to make a backup of our models folder location at ./WorkflowApp/processes/

------------------------------------------------------------------------------------------------------

       there are 29 models that can be impacted
        log file was written to 'upgrade.log'
     if this is a new install, please ignore this message
```

**Comment by linonetwo** [comment]
@ralphhanna I think if you release v2.0.0-prerelease in alpha channel in npm, will solve this?

This is already in your branch.

**Comment by ralphhanna** [comment]
Sorry still get the error:
```
npm i bpmn-server@alpha
```
When I run node setup
```
E:\X4\installed\web>node setup
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'bpmn-server'
Require stack:
- E:\X4\installed\web\index.js
- E:\X4\installed\web\setup.js
←[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:920:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1141:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:110:18)←[39m
    at Object.<anonymous> ←[90m(E:\X4\installed\web\←[39mindex.js:14:14←[90m)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1254:14)←[39m
←[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:1117:32)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:958:12)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1141:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'E:\\X4\\installed\\web\\index.js'←[39m,
    ←[32m'E:\\X4\\installed\\web\\setup.js'←[39m
  ]
}

Node.js v18.16.0

``

index.js
```
E:\X4\installed\web>type index.js
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.docsFolder = void 0;
__exportStar(require('bpmn-server'), exports);
const docsFolder = __dirname + '/node_modules/bpmn-server/docs/';
exports.docsFolder = docsFolder;
//# sourceMappingURL=index.js.map
E:\X4\installed\web>

```
E:\X4\installed\web>type node_modules\bpmn-server\package.json
{
  "name": "bpmn-server",
  "version": "2.0.0-alpha1",
  "description": "BPMN 2.0 Server including Modeling, Execution and Presistence, an open source for Node.js",
  "license": "MIT",
  "scripts": {
    "build": "tsc --build",
    "clean": "rimraf dist",
    "wintest": "node_modules/.bin/mocha",
    "toc": "node scripts/generate-api-toc ./docs/API.md,./docs/Examples.md",
    "test-md": "node scripts/test-markdown.js ./docs/API.md && node scripts/test-markdown.js ./docs/Examples.md"
  },
  "repository": {
    "type": "git",
    "url": "git+https:github.com/ralphhanna/bpmn-server.git"
  },
  "keywords": [
    "BPMN",
    "BPMN 2.0",
    "Workflow",
    "Node.js",
    "TypeScript"
  ],
  "author": {
    "name": "ralphhanna"
  },
  "module": "dist/index.js",
  "types": "dist/index.d.ts",
  "files": [
    "dist/**/*.js",
    "dist/**/*.js.map",
    "dist/**/*.d.ts",
    "README.md"
  ],
  "dependencies": {
    "bcrypt": "^5.0.1",
    "body-parser": "^1.19.0",
    "bpmn-moddle": "^7.0.2",
    "camunda-bpmn-moddle": "^4.4.0",
    "chai": "^4.2.0",
    "chalk": "^2.4.2",
    "compression": "^1.7.4",
    "connect-busboy": "^1.0.0",
    "connect-flash": "^0.1.1",
    "cookie-parser": "^1.4.5",
    "core-js": "^3.6.5",
    "cron-parser": "^2.16.3",
    "debug": "^4.3.1",
    "dotenv": "^8.2.0",
    "errorhandler": "^1.5.1",
    "fs-extra": "^9.1.0",
    "iso8601-duration": "^1.2.0",
    "lodash": "^4.17.20",
    "lusca": "^1.7.0",
    "minimist": "^1.2.8",
    "mocha": "^10.2.0",
    "mocha-cakes-2": "^3.3.0",
    "moment": "^2.29.4",
    "mongodb": "^3.6.0",
    "morgan": "^1.10.0",
    "multer": "*",
    "nock": "^12.0.3",
    "nodemon": "^3.0.1",
    "ts-node": "^8.10.1",
    "uuid": "^8.3.0"
  },
  "devDependencies": {
    "@types/express": "^4.17.7",
    "@types/express-serve-static-core": "^4.17.9",
    "@types/mime": "^1.3.1",
    "@types/node": "^12.12.7",
    "@types/serve-static": "^1.13.5",
    "prettier": "^2.0.5",
    "rimraf": "^5.0.5",
    "tslint": "^6.1.3",
    "tslint-config-prettier": "^1.18.0",
    "typedoc": "^0.25.4",
    "typedoc-plugin-markdown": "^3.17.1",
    "typescript": ">=3.9.7"
  },
  "engines": {
    "node": ">=12.0.0"
  }
}

--

**Comment by linonetwo** [comment]
I will have a try tonight. But maybe you failed to install? Because `bpmn-server` is not showup in your package.json's dependency part

**Comment by linonetwo** [comment]
Also I recommend to use pnpm

**Comment by linonetwo** [comment]
I'm looking at it. Would you delete .js .dts first?

**Comment by linonetwo** [comment]
![图片](https://github.com/bpmnServer/bpmn-web/assets/3746270/15a7ba6a-39db-4d90-92cb-56b177880abf)

looks good now
